[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@aave/=lib/aave-v3-origin/src",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink/"
]
optimizer_runs = 1000000

[fuzz]
runs = 500
fail_on_revert = false
show_metrics = true

[fmt]
line_length = 100
